version: "3.9"

services:
  server:
    build: /
    ports:
        - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: 'qwerty1298'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=qwerty1298 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  my-db: